import { sub } from 'date-fns'
import { create } from 'zustand'

interface TeethStateInterface {
	teethList: toothObject[][][]
	appointment: {
		date: Date
		treatment: string
		const: string
		doctor: string
	}
	setTeethList: (value: TeethStateInterface['teethList']) => void
	toothState: toothStateType
	setToothState: (value: toothStateType) => void
	positionState: toothPositionStateType
	setPositionState: (value: toothPositionStateType) => void
}

const useTeethState = create<TeethStateInterface>()(set => ({
	teethList: [
		[
			[
				{
					tooth: 18,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 17,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 16,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 15,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 14,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 13,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 12,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 11,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
			],
			[
				{
					tooth: 21,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 22,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 23,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 24,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 25,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 26,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 27,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 28,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
			],
		],

		[
			[
				{
					tooth: 55,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 54,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 53,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 52,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 51,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
			],
			[
				{
					tooth: 61,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 62,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 63,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 64,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 65,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
			],
		],

		[
			[
				{
					tooth: 85,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 84,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 83,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 82,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 81,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
			],
			[
				{
					tooth: 71,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 72,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 73,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 74,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 75,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
			],
		],

		[
			[
				{
					tooth: 48,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 47,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 46,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 45,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 44,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 43,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 42,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 41,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
			],
			[
				{
					tooth: 31,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 32,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 33,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 34,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 35,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 36,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 37,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
				{
					tooth: 38,
					toothState: '',
					palatina: '',
					distal: '',
					mesial: '',
					vestibular: '',
					oclusal: '',
				},
			],
		],
	],
	appointment: {
		date: sub(new Date(), {
			years: 1,
		}),
		treatment: '',
		const: '',
		doctor: '',
	},
	setTeethList: value => set(state => ({ ...state, teethList: value })),
	toothState: '',
	setToothState: value => set(state => ({ ...state, toothState: value })),
	positionState: '',
	setPositionState: value => set(state => ({ ...state, positionState: value })),
}))

export default useTeethState
