import { ThemeProvider } from '@mui/material'
import theme from '@/utils/Theme'
import '@/styles/globals.css'

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<ThemeProvider theme={theme}>
				<body>{children}</body>
			</ThemeProvider>
		</html>
	)
}
