import { IUserState } from "@/interface/User";
import { sub } from "date-fns";

export const constantTeethList: Odontogram = {
  permanent: {
    "1": [
      {
        tooth: 18,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 17,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 16,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 15,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 14,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 13,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 12,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 11,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
    ], // Dientes del 11 al 18
    "2": [
      {
        tooth: 21,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 22,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 23,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 24,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 25,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 26,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 27,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 28,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
    ], // Dientes del 21 al 28
    "3": [
      {
        tooth: 48,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 47,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 46,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 45,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 44,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 43,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 42,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 41,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
    ], // Dientes del 41 al 48
    "4": [
      {
        tooth: 31,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 32,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 33,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 34,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 35,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 36,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 37,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 38,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
    ], // Dientes del 31 al 38
  },
  temporary: {
    "5": [
      {
        tooth: 55,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 54,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 53,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 52,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 51,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
    ], // Dientes del 51 al 55
    "6": [
      {
        tooth: 61,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 62,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 63,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 64,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 65,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
    ], // Dientes del 61 al 65
    "7": [
      {
        tooth: 71,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 72,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 73,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 74,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 75,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
    ], // Dientes del 71 al 75
    "8": [
      {
        tooth: 85,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 84,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 83,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 82,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
      {
        tooth: 81,
        toothState: "",
        palatina: "",
        distal: "",
        mesial: "",
        vestibular: "",
        oclusal: "",
      },
    ], // Dientes del 81 al 85
  },
};

export const constantAppointment = {
  date: new Date(),
  treatment: "",
  cost: "",
  doctor: "",
  created_at: new Date(),
  updated_at: new Date(),
};

export enum OrthoTerms {
  SNC = "SNC",
  SVC = "SVC",
  SE = "SE",
  SME = "SME",
  SR = "SR",
  SU = "SU",
  SGU = "SGU",
  SGI = "SGI",
}

export const patientBasicData: PatientDataInterface = {
  name: "",
  birthdate: sub(new Date(), {
    years: 1,
  }),
  direction: "",
  phone: "",
  occupation: "",
  completeOdontogram: false,
  reason: "",
  allergicReactions: "",
  currentSystemicTreatment: "",
  references: "",
  SNC: false,
  SVC: false,
  SE: false,
  SME: false,
  comments1: "",
  SR: false,
  SU: false,
  SGU: false,
  SGI: false,
  comments2: "",
};

export const maxDate = sub(new Date(), {
  years: 1,
});
export const minDate = sub(new Date(), {
  years: 95,
});

export const USERBASIC: IUserState = {
  displayName: null,
  email: null,
  phoneNumber: null,
  photoURL: null,
  providerId: "password",
  uid: "",
};
